ci: test

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,10 +7,9 @@ name: Continous Integration and Deployment (CI/CD)
 on:
   push:
     branches: [ "main" ]
-  #pull_request:
-    #branches: [ "main" ]
 
 permissions:
+  id-token: write
   contents: write
   issues: write
   packages: write
@@ -64,17 +63,10 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Extract version from source
-        id: get_version
-        run: |
-          VERSION=$(grep "__version__" ./src/__init__.py | cut -d '"' -f2)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-
       - name: Build and Save Docker image as tar
         run: |
-          docker build -t ggsbot:${{ env.VERSION }} .
-          docker save ggsbot:${{ env.VERSION }} -o ggsbot.tar
+          docker build -t ggsbot:latest .
+          docker save ggsbot:latest -o ggsbot.tar
 
       - name: Save Docker image as an artifact
         uses: actions/upload-artifact@v4
@@ -84,23 +76,92 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
+    concurrency:
+      group: ${{ github.workflow }}-release-${{ github.ref_name }}
+      cancel-in-progress: false
     needs:
       - test
       - build
 
     steps:
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Checkout Repository on Release Branch
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.ref_name }}
+          fetch-depth: 0
+  
+      - name: Force release branch to be at workflow SHA
+        run: |
+          git reset --hard ${{ github.sha }}
+
       - name: Download Docker image artifact
         uses: actions/download-artifact@v4
         with:
           name: docker-image
 
+      - name: Verify upstream has NOT changed
+        # Last chance to abort before causing an error as another PR/push was applied to
+        # the upstream branch while this workflow was running. This is important
+        # because we are committing a version change (--commit). You may omit this step
+        # if you have 'commit: false' in your configuration.
+        #
+        # You may consider moving this to a repo script and call it from this step instead
+        # of writing it in-line.
+        shell: bash
+        run: |
+          set +o pipefail
+
+          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
+          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+
+          set -o pipefail
+
+          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+              exit 1
+          fi
+
+          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+
+          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+              exit 1
+          fi
+
+          HEAD_SHA="$(git rev-parse HEAD)"
+
+          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+              exit 1
+          fi
+
+          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+
+      - name: Semantic Version Release
+        id: release
+        uses: python-semantic-release/python-semantic-release@v9.21.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          git_committer_name: "github-actions"
+          git_committer_email: "actions@users.noreply.github.com"
+          commit: true
+          tag: true
+          push: true
+          changelog: true
+
       - name: Tag Docker image with version
+        if: steps.release.outputs.released == 'true'
         run: |
           docker load -i ./ggsbot.tar
-          docker tag ggsbot:latest ggsbot:${{ steps.semantic_release.outputs.tag }}
+          docker tag ggsbot:latest ggsbot:${{ steps.release.outputs.tag }}
       
       - name: Create GitHub Release
+        if: steps.release.outputs.released == 'true'
         uses: softprops/action-gh-release@v2
         with:
           files: ./ggsbot.tar
-          tag_name: ${{ steps.semantic_release.outputs.tag }}
+          tag_name: ${{ steps.release.outputs.tag }}
